enum ActionType {
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  BANK_WITHDRAW = 'BANK_WITHDRAW',
  BANK_BANKRUPT = 'BANKRUPT',

  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
}

export default ActionType
